name: example
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
#  i

# f

flutter:
  fonts:
    - family: myiconfont
      fonts:
        - asset: assets/fonts/test_icons/iconfont.ttf
        - asset: assets/fonts/my_icons/iconfont.ttf
        - asset: assets/fonts/my_icons1/iconfont.ttf
  uses-material-design: true