name: example
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  iconfont:
    path: ..

environment:
  sdk: ">=2.7.0 <3.0.0"

iconfont:
  - icons: 
    - css: //at.alicdn.com/t/font_1500681_sz0skwerbw.css
      dir: test_icons
    in: assets/fonts2
    out: lib/icons/

  - icons: 
    - css: //at.alicdn.com/t/font_1500681_sz0skwerbw.css
      dir: my_icons

  - icons:
    - css: //at.alicdn.com/t/font_1932408_c19dd499jfh.css
      dir: my_icons2
  
flutter:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/my_icons2/iconfont.ttf
    - family: myiconfont
      fonts:
        - asset: assets/fonts0/my_icons/iconfont.ttf
        - asset: assets/fonts1/test_icons/iconfont.ttf
        - asset: assers/fonts2/test_icons/iconfont.ttf
        - asset: assets/fonts/my_icons/iconfont.ttf
        - asset: assets/fonts2/test_icons/iconfont.ttf