name: iconfont
description: Dart library to generate Dart model class from IconFont files.
version: 0.7.0
author: chuanci<chuanci@vip.qq.com>
homepage: https://github.com/chuanci/iconfont

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  pubspec_yaml: ^2.0.1
  args: ^1.6.0
  path: ^1.6.4
  dio: ^3.0.9

executables:
  iconfont: